name: Upload Build Artifacts
description: 'Upload ESBuild build artifacts'
outputs:
  hashed:
    description: 'Hashed branch name'
    value: ${{ steps.hash_current_branch_name.outputs.hashed }}

runs:
  using: 'composite'
  steps:
    - name: Hash Current Branch Name
      id: hash_current_branch_name
      run: |
        hashed_name=$(echo -n "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | base64 -w 0)
        echo "hashed=${hashed_name}">> $GITHUB_OUTPUT
      shell: 'bash'
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{steps.hash_current_branch_name.outputs.hashed}}
        path: |
          **/dist/**
          ./translations/*.ts
          !**/node_modules/**
        retention-days: 30
        overwrite: true
