import { WalletInfo, WalletState, WalletType } from '../../types/wallet';

export const walletsInfo: WalletInfo[] = [
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.CONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.CONNECTING,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.NOT_INSTALLED,
    type: WalletType.COINBASE,
    installLink:
      'https://chrome.google.com/webstore/detail/coinbase-wallet-extension/hnfanknocfeofbddgcijnmhnfnkdnaad?hl=en',
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.CONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletType.COINBASE,
  },
];
