project_id_env: REACT_APP_CROWDIN_PROJECT_ID # Your Crowdin project ID
api_token_env: REACT_APP_CROWDIN_API_KEY

preserve_hierarchy: true

files: # Paths to the source and translation files
  - source:  /translations/en/messages.po
    translation: /translations/%two_letters_code%/%original_file_name%