import { WalletInfo, WalletState } from '../../components';
import { WalletTypes } from '@rango-dev/wallets-shared';

export const walletsInfo: WalletInfo[] = [
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.CONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.CONNECTING,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.NOT_INSTALLED,
    type: WalletTypes.COINBASE,

    link: 'https://chrome.google.com/webstore/detail/coinbase-wallet-extension/hnfanknocfeofbddgcijnmhnfnkdnaad?hl=en',
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.CONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    title: 'Coinbase',
    state: WalletState.DISCONNECTED,
    link: '',
    type: WalletTypes.COINBASE,
  },
];
