import { WalletInfo, WalletState } from '../../types/wallet';
import { WalletTypes } from '@rango-dev/wallets-shared';

export const walletsInfo: WalletInfo[] = [
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.CONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.CONNECTING,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.NOT_INSTALLED,
    type: WalletTypes.COINBASE,
    showOnMobile: true,
    installLink:
      'https://chrome.google.com/webstore/detail/coinbase-wallet-extension/hnfanknocfeofbddgcijnmhnfnkdnaad?hl=en',
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.CONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
  {
    image: 'https://app.rango.exchange/wallets/coinbase.svg',
    name: 'Coinbase',
    state: WalletState.DISCONNECTED,
    installLink: '',
    type: WalletTypes.COINBASE,
    showOnMobile: true,
  },
];
