import { LiquiditySource } from '../../types/meta';

export const liquiditySources: LiquiditySource[] = [
  {
    title: 'Pancake',
    logo: 'https://api.rango.exchange/swappers/pancake-swap.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'ThorChain',
    logo: 'https://api.rango.exchange/swappers/Thorchain.svg',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Horizon Bridge',
    logo: 'https://api.rango.exchange/swappers/harmony-horizon.svg',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: '1Inch',
    logo: 'https://api.rango.exchange/swappers/1inch.svg',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'OpenOcean',
    logo: 'https://api.rango.exchange/swappers/openocean.svg',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'SushiSwap',
    logo: 'https://api.rango.exchange/swappers/sushi.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'OkcSwap',
    logo: 'https://api.rango.exchange/swappers/okcswap.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'CherrySwap',
    logo: 'https://api.rango.exchange/swappers/cherry-swap.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'Osmosis',
    logo: 'https://api.rango.exchange/swappers/osmosis.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'Osmosis',
    logo: 'https://api.rango.exchange/swappers/osmosis.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'SolanaWrapper',
    logo: 'https://api.rango.exchange/tokens/SOLANA/SOL.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'Jupiter',
    logo: 'https://api.rango.exchange/swappers/jupiter.svg',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'stargate',
    logo: 'https://api.rango.exchange/swappers/stargate.svg',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Multichain',
    logo: 'https://api.rango.exchange/swappers/multichain.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Satellite',
    logo: 'https://api.rango.exchange/swappers/satellite.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Diffusion',
    logo: 'https://api.rango.exchange/swappers/diffusion.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'JunoSwap',
    logo: 'https://api.rango.exchange/swappers/junoswap.svg',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'JunoSwap',
    logo: 'https://api.rango.exchange/swappers/junoswap.svg',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'PangolinSwap',
    logo: 'https://api.rango.exchange/swappers/pangolin.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'MMFinance',
    logo: 'https://api.rango.exchange/swappers/mm-finance.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'CronaSwap',
    logo: 'https://api.rango.exchange/swappers/crona.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'VVSFinance',
    logo: 'https://api.rango.exchange/swappers/vvs-finance.svg',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'MDexHeco',
    logo: 'https://api.rango.exchange/swappers/mdex.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'ParaSwap',
    logo: 'https://api.rango.exchange/swappers/para-swap.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'AuroraSwap',
    logo: 'https://api.rango.exchange/swappers/aurora-swap.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'Across',
    logo: 'https://api.rango.exchange/swappers/across.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Arbitrum Bridge',
    logo: 'https://api.rango.exchange/swappers/arbitrum-bridge.svg',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'TrisolarisSwap',
    logo: 'https://api.rango.exchange/swappers/trisolaris.svg',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'Polygon Bridge',
    logo: 'https://api.rango.exchange/swappers/polygon-bridge.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'SpookySwap',
    logo: 'https://api.rango.exchange/swappers/spooky-swap.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'Voyager',
    logo: 'https://api.rango.exchange/swappers/voyager.svg',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Rainbow Bridge',
    logo: 'https://api.rango.exchange/swappers/rainbow-bridge.svg',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Lido',
    logo: 'https://api.rango.exchange/swappers/lido.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Symbiosis',
    logo: 'https://api.rango.exchange/swappers/symbiosis.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Avalanche Bridge',
    logo: 'https://api.rango.exchange/swappers/avalanche-bridge.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'VoltageSwap',
    logo: 'https://api.rango.exchange/swappers/voltage.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'XYFinance',
    logo: 'https://api.rango.exchange/swappers/xy.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'cBridge v2.0',
    logo: 'https://api.rango.exchange/swappers/cbridge.png',
    type: 'AGGREGATOR',
    selected: true,
  },
  {
    title: 'Hyphen',
    logo: 'https://api.rango.exchange/swappers/hyphen.svg',
    type: 'AGGREGATOR',
    selected: true,
  },
  {
    title: 'Optimism Bridge',
    logo: 'https://api.rango.exchange/swappers/optimism.svg',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'OolongSwap',
    logo: 'https://api.rango.exchange/swappers/oolong.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'QuickSwap',
    logo: 'https://api.rango.exchange/swappers/quick-swap.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'StellaSwap',
    logo: 'https://api.rango.exchange/swappers/stella.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'ViperSwap',
    logo: 'https://api.rango.exchange/swappers/viper.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'FinKujira',
    logo: 'https://api.rango.exchange/swappers/finkujira.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'Hop',
    logo: 'https://api.rango.exchange/swappers/hop.svg',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'BeamSwap',
    logo: 'https://api.rango.exchange/swappers/beam-swap.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'SolarbeamSwap',
    logo: 'https://api.rango.exchange/swappers/solarbeamlogo.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'Sifchain',
    logo: 'https://api.rango.exchange/swappers/sifchain.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'Sifchain',
    logo: 'https://api.rango.exchange/swappers/sifchain.png',
    type: 'DEX',
    selected: true,
  },
  {
    title: 'Wormhole',
    logo: 'https://api.rango.exchange/swappers/wormhole.png',
    type: 'BRIDGE',
    selected: true,
  },
  {
    title: 'UniSwapV2',
    logo: 'https://api.rango.exchange/swappers/uniswap.png',
    type: 'DEX',
    selected: true,
  },
];
