export const blockchains = [
  {
    name: 'ETH',
    defaultDecimals: 18,
    addressPatterns: ['^(0x)[0-9A-Fa-f]{40}$'],
    feeAssets: [
      {
        blockchain: 'ETH',
        symbol: 'ETH',
        address: null,
      },
    ],
    logo: 'https://raw.githubusercontent.com/rango-exchange/assets/main/blockchains/ETH/icon.svg',
    displayName: 'Ethereum',
    shortName: 'ETH',
    sort: 0,
    color: '#ecf0f1',
    enabled: true,
    type: 'EVM',
    chainId: '0x1',
    info: {
      infoType: 'EvmMetaInfo',
      chainName: 'Ethereum Mainnet',
      nativeCurrency: {
        name: 'ETH',
        symbol: 'ETH',
        decimals: 18,
      },
      rpcUrls: ['https://rpc.ankr.com/eth'],
      blockExplorerUrls: ['https://etherscan.io'],
      addressUrl: 'https://etherscan.io/address/{wallet}',
      transactionUrl: 'https://etherscan.io/tx/{txHash}',
      enableGasV2: true,
    },
  },
  {
    name: 'BSC',
    defaultDecimals: 18,
    addressPatterns: ['^(0x)[0-9A-Fa-f]{40}$'],
    feeAssets: [
      {
        blockchain: 'BSC',
        symbol: 'BNB',
        address: null,
      },
    ],
    logo: 'https://raw.githubusercontent.com/rango-exchange/assets/main/blockchains/BSC/icon.svg',
    displayName: 'BNB Smart Chain',
    shortName: 'BSC',
    sort: 1,
    color: '#F3BA2F',
    enabled: true,
    type: 'EVM',
    chainId: '0x38',
    info: {
      infoType: 'EvmMetaInfo',
      chainName: 'Binance Smart Chain Mainnet',
      nativeCurrency: {
        name: 'BNB',
        symbol: 'BNB',
        decimals: 18,
      },
      rpcUrls: ['https://bsc-dataseed1.ninicoin.io'],
      blockExplorerUrls: ['https://bscscan.com'],
      addressUrl: 'https://bscscan.com/address/{wallet}',
      transactionUrl: 'https://bscscan.com/tx/{txHash}',
      enableGasV2: false,
    },
  },
  {
    name: 'POLYGON',
    defaultDecimals: 18,
    addressPatterns: ['^(0x)[0-9A-Fa-f]{40}$'],
    feeAssets: [
      {
        blockchain: 'POLYGON',
        symbol: 'MATIC',
        address: null,
      },
    ],
    logo: 'https://raw.githubusercontent.com/rango-exchange/assets/main/blockchains/POLYGON/icon.svg',
    displayName: 'Polygon',
    shortName: 'Polygon',
    sort: 3,
    color: '#8247E5',
    enabled: true,
    type: 'EVM',
    chainId: '0x89',
    info: {
      infoType: 'EvmMetaInfo',
      chainName: 'Polygon Mainnet',
      nativeCurrency: {
        name: 'MATIC',
        symbol: 'MATIC',
        decimals: 18,
      },
      rpcUrls: ['https://polygon-rpc.com'],
      blockExplorerUrls: ['https://polygonscan.com'],
      addressUrl: 'https://polygonscan.com/address/{wallet}',
      transactionUrl: 'https://polygonscan.com/tx/{txHash}',
      enableGasV2: true,
    },
  },
  {
    name: 'TRON',
    defaultDecimals: 18,
    addressPatterns: ['^T[1-9A-HJ-NP-Za-km-z]{33}$'],
    feeAssets: [
      {
        blockchain: 'TRON',
        symbol: 'TRX',
        address: null,
      },
    ],
    logo: 'https://raw.githubusercontent.com/rango-exchange/assets/main/blockchains/TRON/icon.svg',
    displayName: 'Tron',
    shortName: 'Tron',
    sort: 11,
    color: '#FF060A',
    enabled: true,
    type: 'TRON',
    chainId: '0x2b6653dc',
    info: {
      infoType: 'EvmMetaInfo',
      chainName: 'TRON Mainnet',
      nativeCurrency: {
        name: 'TRX',
        symbol: 'TRX',
        decimals: 6,
      },
      rpcUrls: ['https://api.trongrid.io/jsonrpc'],
      blockExplorerUrls: ['https://tronscan.org/#'],
      addressUrl: 'https://tronscan.org/#/address/{wallet}',
      transactionUrl: 'https://tronscan.org/#/tx/{txHash}',
      enableGasV2: false,
    },
  },
  {
    name: 'BTC',
    defaultDecimals: 8,
    addressPatterns: [
      '^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$|^(bc1)[0-9A-Za-z]{39,59}$',
    ],
    feeAssets: [
      {
        blockchain: 'BTC',
        symbol: 'BTC',
        address: null,
      },
    ],
    logo: 'https://raw.githubusercontent.com/rango-exchange/assets/main/blockchains/BTC/icon.svg',
    displayName: 'Bitcoin',
    shortName: 'BTC',
    sort: 12,
    color: '#F7931A',
    enabled: true,
    type: 'TRANSFER',
    chainId: null,
    info: null,
  },
  {
    name: 'COSMOS',
    defaultDecimals: 6,
    addressPatterns: ['^(cosmos1)[0-9a-z]{38}$'],
    feeAssets: [
      {
        blockchain: 'COSMOS',
        symbol: 'ATOM',
        address: null,
      },
    ],
    logo: 'https://raw.githubusercontent.com/rango-exchange/assets/main/blockchains/COSMOS/icon.svg',
    displayName: 'Cosmos',
    shortName: 'Cosmos',
    sort: 14,
    color: '#2E3148',
    enabled: true,
    type: 'COSMOS',
    chainId: 'cosmoshub-4',
    info: {
      infoType: 'CosmosMetaInfo',
      experimental: false,
      rpc: 'https://cosmos-rpc.polkachu.com',
      rest: 'https://lcd-cosmoshub.blockapsis.com',
      cosmostationLcdUrl: 'https://lcd-cosmoshub.blockapsis.com',
      cosmostationApiUrl: 'https://cosmos-rpc.polkachu.com',
      cosmostationDenomTracePath: '/ibc/apps/transfer/v1/denom_traces/',
      mintScanName: 'cosmos',
      chainName: 'Cosmos',
      stakeCurrency: {
        coinDenom: 'ATOM',
        coinMinimalDenom: 'uatom',
        coinDecimals: 6,
        coinGeckoId: 'cosmos',
        coinImageUrl: '/tokens/blockchain/cosmos.svg',
      },
      bip44: {
        coinType: 118,
      },
      bech32Config: {
        bech32PrefixAccAddr: 'cosmos',
        bech32PrefixAccPub: 'cosmospub',
        bech32PrefixValAddr: 'cosmosvaloper',
        bech32PrefixValPub: 'cosmosvaloperpub',
        bech32PrefixConsAddr: 'cosmosvalcons',
        bech32PrefixConsPub: 'cosmosvalconspub',
      },
      currencies: [
        {
          coinDenom: 'ATOM',
          coinMinimalDenom: 'uatom',
          coinDecimals: 6,
          coinGeckoId: 'cosmos',
          coinImageUrl: '/tokens/blockchain/cosmos.svg',
        },
      ],
      feeCurrencies: [
        {
          coinDenom: 'ATOM',
          coinMinimalDenom: 'uatom',
          coinDecimals: 6,
          coinGeckoId: 'cosmos',
          coinImageUrl: '/tokens/blockchain/cosmos.svg',
        },
      ],
      features: ['stargate', 'ibc-transfer'],
      explorerUrlToTx: 'https://www.mintscan.io/cosmos/txs/{txHash}',
      gasPriceStep: {
        low: 0.01,
        average: 0.025,
        high: 0.04,
      },
    },
  },
];
