// TODO: fix ts errors
// eslint-disable-next-line
// @ts-nocheck
import type { TokenWithAmount } from './TokenList';

export const tokensMeta: TokenWithAmount[] = [
  {
    blockchain: 'TRON',
    symbol: 'BTC',
    image: 'https://api.rango.exchange/i/VTDf13',
    address: 'TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9',
    usdPrice: 30412.85212694868,
    decimals: 8,
    name: 'Bitcoin',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: 'SunSwap Default List',
    coinSourceUrl: 'https://api.rango.exchange/i/wzgyM7',
    supportedSwappers: ['SunSwap'],
  },
  {
    blockchain: 'ETH',
    symbol: 'BTC',
    image: 'https://api.rango.exchange/i/J86dSE',
    address: '0xb6ed7644c69416d67b522e20bc294a9a9b405b31',
    usdPrice: 30412.85212694868,
    decimals: 8,
    name: 'Bitcoin Token',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['Arbitrum Bridge'],
  },
  {
    blockchain: 'ARBITRUM',
    symbol: 'BTC',
    image: 'https://api.rango.exchange/i/J86dSE',
    address: '0x7cb16cb78ea464ad35c8a50abf95dff3c9e09d5d',
    usdPrice: 30412.85212694868,
    decimals: 8,
    name: 'Bitcoin Token',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['Arbitrum Bridge'],
  },
  {
    blockchain: 'FANTOM',
    symbol: 'BTC',
    image: 'https://api.rango.exchange/i/WtP1yp',
    address: '0x321162cd933e2be498cd2267a90534a804051b11',
    usdPrice: 30412.85212694868,
    decimals: 8,
    name: 'Bitcoin',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: [
      'SpookySwap',
      'AnySwap',
      'OpenOceanFantom',
      'SpiritSwapV2',
    ],
  },
  {
    blockchain: 'SOLANA',
    symbol: 'BTC',
    image: 'https://api.rango.exchange/i/elAFzy',
    address: '9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E',
    usdPrice: 30831.0,
    decimals: 6,
    name: 'Wrapped Bitcoin (Sollet)',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['Jupiter'],
  },
  {
    blockchain: 'BTC',
    symbol: 'BTC',
    image: 'https://api.rango.exchange/tokens/BTC/BTC.png',
    address: null,
    usdPrice: 30412.85212694868,
    decimals: 8,
    name: null,
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['ThorChain', 'MayaProtocol'],
  },
  {
    blockchain: 'ARBITRUM',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/MTyH5i',
    address: null,
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'ETH',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: [
      'Arbitrum Bridge',
      'AnySwap',
      'Synapse Bridge',
      'Hyphen',
      'cBridge v2.0',
      'stargate',
      'Voyager',
      'Across',
      'ParaSwap Arbitrum',
      'XY Finance',
      'SushiArbitrum',
      'Orbiter',
      'OneInchArbitrum',
    ],
  },
  {
    blockchain: 'BSC',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/qr4L6S',
    address: '0x2170ed0880ac9a755fd29b2688956bd959f933f8',
    usdPrice: 1873.6358110305832,
    decimals: 18,
    name: 'Binance Pegged ETH',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: 'PancakeSwap Extended',
    coinSourceUrl: 'https://api.rango.exchange/i/zsiskx',
    supportedSwappers: [
      'ParaSwap Bsc',
      'AnySwap',
      'OneInchBsc',
      'Hyphen',
      'PancakeSwapBsc',
      'cBridge v2.0',
      'Voyager',
      'Orbiter',
    ],
  },
  {
    blockchain: 'TRON',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/9QHuSO',
    address: 'THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF',
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Ethereum',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: 'SunSwap Default List',
    coinSourceUrl: 'https://api.rango.exchange/i/wzgyM7',
    supportedSwappers: ['SunSwap'],
  },
  {
    blockchain: 'ETH',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/j9xgdC',
    address: null,
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Ethereum',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: [
      'Wormhole',
      'ThorChain',
      'Arbitrum Bridge',
      'AnySwap',
      'Synapse Bridge',
      'Hyphen',
      'Satellite',
      'cBridge v2.0',
      'Optimism Bridge',
      'MayaProtocol',
      'stargate',
      'Voyager',
      'Across',
      'Lido',
      'OneInchEth',
      'Polygon Bridge',
      'XY Finance',
      'Rainbow Bridge',
      'ParaSwap Eth',
      'Orbiter',
    ],
  },
  {
    blockchain: 'OPTIMISM',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/j9xgdC',
    address: null,
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Optimism',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: [
      'XY Finance',
      'OneInchOptimism',
      'AnySwap',
      'OpenOceanOptimism',
      'Hyphen',
      'Optimism Bridge',
      'cBridge v2.0',
      'ParaSwap Optimism',
      'stargate',
      'Voyager',
      'Orbiter',
      'Across',
    ],
  },
  {
    blockchain: 'TELOS',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/j9xgdC',
    address: '0xfa9343c3897324496a05fc75abed6bac29f8a40f',
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Ethereum',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['AnySwap'],
  },
  {
    blockchain: 'HECO',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/j9xgdC',
    address: '0x64ff637fb478863b7468bc97d30a5bf3a428a1fd',
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Heco-Peg ETH Token',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['AnySwap', 'MDexHeco'],
  },
  {
    blockchain: 'FANTOM',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/j9xgdC',
    address: '0x74b23882a30290451a17c44f4f05243b6b58c76d',
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Ethereum',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: [
      'SpookySwap',
      'AnySwap',
      'OpenOceanFantom',
      'SpiritSwapV2',
      'cBridge v2.0',
    ],
  },
  {
    blockchain: 'KCC',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/j9xgdC',
    address: '0xf55af137a98607f7ed2efefa4cd2dfe70e4253b1',
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'KCC-Peg Ether',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['AnySwap', 'Mojito'],
  },
  {
    blockchain: 'POLYGONZK',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/j9xgdC',
    address: null,
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Polygon zkEVM',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['OpenOceanPolygonZk', 'AnySwap', 'cBridge v2.0'],
  },
  {
    blockchain: 'BRISE',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/j9xgdC',
    address: '0x6ab6d61428fde76768d7b45d8bfeec19c6ef91a8',
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Ethereum',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['AnySwap'],
  },
  {
    blockchain: 'SOLANA',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/wNnplE',
    address: '7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs',
    usdPrice: 1871.812897031218,
    decimals: 8,
    name: 'Ether (Portal)',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['Wormhole', 'Jupiter'],
  },
  {
    blockchain: 'ZKSYNC',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/MTyH5i',
    address: null,
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Ether',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['SpaceFi', 'XY Finance', 'OneInchZksync'],
  },
  {
    blockchain: 'ETH',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/ScLyt4',
    address: '0x0d505c03d30e65f6e9b4ef88855a47a89e4b7676',
    usdPrice: 2.595267895338006e-5,
    decimals: 18,
    name: 'Zoomer',
    isPopular: false,
    isSecondaryCoin: true,
    coinSource: 'CoinGecko',
    coinSourceUrl: 'https://api.rango.exchange/tokens/SOURCES/COINGECKO.png',
    supportedSwappers: ['ParaSwap Eth', 'OneInchEth'],
  },
  {
    blockchain: 'BOBA',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/MTyH5i',
    address: null,
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'ETH',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['cBridge v2.0', 'Orbiter', 'OolongSwap'],
  },
  {
    blockchain: 'AURORA',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/E13Iyb',
    address: null,
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Ethereum',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['Rainbow Bridge', 'OpenOceanAurora'],
  },
  {
    blockchain: 'MOONRIVER',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/i/pZI3Eh',
    address: '0x639a647fbe20b6c8ac19e48e2de44ea792c62c5c',
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: 'Ethereum',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['SolarbeamSwap', 'OpenOceanMoonRiver'],
  },
  {
    blockchain: 'BNB',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/tokens/ETH/ETH.png',
    address: '1c9',
    usdPrice: 1871.812897031218,
    decimals: 8,
    name: null,
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['ThorChain'],
  },
  {
    blockchain: 'STARKNET',
    symbol: 'ETH',
    image: 'https://api.rango.exchange/tokens/ETH/ETH.png',
    address:
      '0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7',
    usdPrice: 1871.812897031218,
    decimals: 18,
    name: null,
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['Orbiter', '10KSwap'],
  },
  {
    blockchain: 'ARBITRUM',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/JcLHV6',
    address: '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: 'Arb Whitelist Era',
    coinSourceUrl: 'https://api.rango.exchange/i/yjuezQ',
    supportedSwappers: [
      'Arbitrum Bridge',
      'AnySwap',
      'Synapse Bridge',
      'Hyphen',
      'cBridge v2.0',
      'stargate',
      'Across',
      'ParaSwap Arbitrum',
      'XY Finance',
      'Synapse Swapper',
      'SushiArbitrum',
      'Orbiter',
      'OneInchArbitrum',
    ],
  },
  {
    blockchain: 'BSC',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/6837hX',
    address: '0x55d398326f99059ff775485246999027b3197955',
    usdPrice: 1.001,
    decimals: 18,
    name: 'Binance Pegged USDT',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: 'PancakeSwap Extended',
    coinSourceUrl: 'https://api.rango.exchange/i/zsiskx',
    supportedSwappers: [
      'XY Finance',
      'ParaSwap Bsc',
      'Synapse Swapper',
      'AnySwap',
      'OneInchBsc',
      'Synapse Bridge',
      'Hyphen',
      'PancakeSwapBsc',
      'cBridge v2.0',
      'stargate',
    ],
  },
  {
    blockchain: 'BSC',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/mZTSbe',
    address: '0x524bc91dc82d6b90ef29f76a3ecaabafffd490bc',
    usdPrice: 152.11233445513386,
    decimals: 6,
    name: 'USDT (wormhole)',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: 'Rango Token List',
    coinSourceUrl: 'https://api.rango.exchange/i/lYlZID',
    supportedSwappers: [
      'Wormhole',
      'ParaSwap Bsc',
      'OneInchBsc',
      'PancakeSwapBsc',
    ],
  },
  {
    blockchain: 'TRON',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/IeVOL2',
    address: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: 'SunSwap Default List',
    coinSourceUrl: 'https://api.rango.exchange/i/wzgyM7',
    supportedSwappers: ['AllBridge', 'SunSwap'],
  },
  {
    blockchain: 'POLYGON',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/r3Oex6',
    address: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: 'Quickswap Token List',
    coinSourceUrl: 'https://api.rango.exchange/i/uFuqhg',
    supportedSwappers: [
      'AnySwap',
      'Synapse Bridge',
      'Hyphen',
      'cBridge v2.0',
      'stargate',
      'Across',
      'Polygon Bridge',
      'XY Finance',
      'Synapse Swapper',
      'ParaSwap Polygon',
      'QuickSwap',
      'OneInchPolygon',
      'Orbiter',
    ],
  },
  {
    blockchain: 'OKC',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/tGa1q2',
    address: '0x382bb369d343125bfb2117af9c149795c6c65c50',
    usdPrice: 1.001,
    decimals: 18,
    name: 'Tether',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['AnySwap', 'OkcSwap', 'CherrySwap'],
  },
  {
    blockchain: 'ETH',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/YXKZob',
    address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: [
      'Wormhole',
      'Arbitrum Bridge',
      'ThorChain',
      'AnySwap',
      'Synapse Bridge',
      'Hyphen',
      'Optimism Bridge',
      'cBridge v2.0',
      'MayaProtocol',
      'stargate',
      'Across',
      'Avalanche Bridge',
      'OneInchEth',
      'Polygon Bridge',
      'XY Finance',
      'Synapse Swapper',
      'Rainbow Bridge',
      'ParaSwap Eth',
      'Orbiter',
    ],
  },
  {
    blockchain: 'OPTIMISM',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/GJxbOP',
    address: '0x94b008aa00579c1307b0ef2c499ad98a8ce58e58',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: [
      'XY Finance',
      'OneInchOptimism',
      'AnySwap',
      'OpenOceanOptimism',
      'Hyphen',
      'Optimism Bridge',
      'cBridge v2.0',
      'ParaSwap Optimism',
      'Orbiter',
      'Across',
    ],
  },
  {
    blockchain: 'CRONOS',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/GJxbOP',
    address: '0x66e428c3f67a68878562e79a0234c1f83c208770',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: [
      'XY Finance',
      'VVSFinance',
      'CronaSwap',
      'AnySwap',
      'OpenOceanCronos',
    ],
  },
  {
    blockchain: 'TELOS',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/GJxbOP',
    address: '0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['AnySwap'],
  },
  {
    blockchain: 'KCC',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/GJxbOP',
    address: '0x0039f574ee5cc39bdd162e9a88e3eb1f111baf48',
    usdPrice: 1.0001031863278,
    decimals: 18,
    name: 'KCC-Peg Tether USD',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['AnySwap', 'Mojito'],
  },
  {
    blockchain: 'POLYGONZK',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/GJxbOP',
    address: '0x1e4a5963abfd975d8c9021ce480b42188849d41d',
    usdPrice: 1.0001031863278,
    decimals: 6,
    name: 'Tether USD',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['OpenOceanPolygonZk', 'AnySwap'],
  },
  {
    blockchain: 'BRISE',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/GJxbOP',
    address: '0xe3f5a90f9cb311505cd691a46596599aa1a0ad7d',
    usdPrice: 1.0001031863278,
    decimals: 6,
    name: 'Tether USD',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['AnySwap'],
  },
  {
    blockchain: 'AVAX_CCHAIN',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/GJxbOP',
    address: '0x9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7',
    usdPrice: 1.001,
    decimals: 6,
    name: 'TetherToken',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: [
      'XY Finance',
      'ParaSwap Avalanche',
      'AnySwap',
      'PangolinSwap',
      'stargate',
    ],
  },
  {
    blockchain: 'POLYGON',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/mZTSbe',
    address: '0x9417669fbf23357d2774e9d421307bd5ea1006d2',
    usdPrice: 1.0001031863278,
    decimals: 6,
    name: 'Tether USD (Wormhole)',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['Wormhole', 'ParaSwap Polygon', 'OneInchPolygon'],
  },
  {
    blockchain: 'SOLANA',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/uhQV48',
    address: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
    usdPrice: 1.001,
    decimals: 6,
    name: 'USDT',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['Jupiter'],
  },
  {
    blockchain: 'POLYGON',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/ICZdda',
    address: '0x3553f861dec0257bada9f8ed268bf0d74e45e89c',
    usdPrice: 0.8972324748880173,
    decimals: 6,
    name: 'USDT (wormhole)',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: 'https://api.rango.exchange/i/lYlZID',
    supportedSwappers: ['ParaSwap Polygon', 'OneInchPolygon'],
  },
  {
    blockchain: 'GNOSIS',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/aR1yFx',
    address: '0x4ecaba5870353805a9f068101a40e0f32ed605c6',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether on xDai',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['OpenOceanGnosis', 'OneInchGnosis'],
  },
  {
    blockchain: 'FUSE',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/ijzpuA',
    address: '0xfadbbf8ce7d5b7041be672561bba99f79c532e10',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD on Fuse',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: 'Voltage Swap List',
    coinSourceUrl: 'https://api.rango.exchange/i/QKm8MZ',
    supportedSwappers: ['VoltageSwap'],
  },
  {
    blockchain: 'MOONBEAM',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/7uIRNT',
    address: '0x81ecac0d6be0550a00ff064a4f9dd2400585fe9c',
    usdPrice: 1.0001031863278,
    decimals: 6,
    name: 'Tether USD (Celer)',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['cBridge v2.0'],
  },
  {
    blockchain: 'AURORA',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/7uIRNT',
    address: '0x4988a896b1227218e4a686fde5eabdcabd91571f',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['Rainbow Bridge', 'cBridge v2.0', 'OpenOceanAurora'],
  },
  {
    blockchain: 'BOBA',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/zoZp6q',
    address: '0x5de1677344d3cb0d7d465c10b72a8f60699c062d',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether USD',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['OpenOceanBoba', 'OolongSwap'],
  },
  {
    blockchain: 'HECO',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/P32K3W',
    address: '0xa71edc38d189767582c38a3145b5873052c3e47a',
    usdPrice: 1.0001571091905554,
    decimals: 18,
    name: 'Heco-Peg USDT Token',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: 'MDEX Heco token List',
    coinSourceUrl: 'https://api.rango.exchange/i/6dySNE',
    supportedSwappers: ['MDexHeco'],
  },
  {
    blockchain: 'AVAX_CCHAIN',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/ICZdda',
    address: '0xf0ff231e3f1a50f83136717f287adab862f89431',
    usdPrice: 1.0001031863278,
    decimals: 6,
    name: 'USDT (wormhole)',
    isPopular: false,
    isSecondaryCoin: false,
    coinSource: 'Rango Token List',
    coinSourceUrl: 'https://api.rango.exchange/i/lYlZID',
    supportedSwappers: ['ParaSwap Avalanche'],
  },
  {
    blockchain: 'MOONRIVER',
    symbol: 'USDT',
    image: 'https://api.rango.exchange/i/HAlx1Q',
    address: '0xb44a9b6905af7c801311e8f4e76932ee959c663c',
    usdPrice: 1.001,
    decimals: 6,
    name: 'Tether',
    isPopular: true,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    supportedSwappers: ['XY Finance', 'SolarbeamSwap', 'OpenOceanMoonRiver'],
  },
];
