// These are old icons
export { AddWalletIcon } from './AddWalletIcon';
export { HorizontalSwapIcon } from './HorizontalSwapIcon';
export { SignatureIcon } from './SignatureIcon';

// These are new icons
export { InfoRegularIcon } from './InfoRegularIcon';
export { CheckCircleIcon } from './CheckCircleIcon';
export { CheckIcon } from './CheckIcon';
export { WarningIcon } from './WarningIcon';
export { HistoryIcon } from './HistoryIcon';
export { GasIcon } from './GasIcon';
export { SettingsIcon } from './SettingIcon';
export { TrashIcon } from './TrashIcon';
export { SearchIcon } from './SearchIcon';
export { AngleRightIcon } from './AngleRightIcon';
export { AngleUpIcon } from './AngleUpIcon';
export { AngleDownIcon } from './AngleDownIcon';
export { AngleLeftIcon } from './AngleLeftIcon';
export { DownloadIcon } from './DownloadIcon';
export { ArrowRightIcon } from './ArrowRightIcon';
export { VerticalSwapIcon } from './VerticalSwapIcon';
export { RetryIcon } from './RetryIcon';
export { WalletIcon } from './WalletIcon';
export { DisconnectIcon } from './DisconnectIcon';
export { TimeIcon } from './TimeIcon';
export { CloseIcon } from './CloseIcon';
export { CopyIcon } from './CopyIcon';
export { NotificationIcon } from './NotificationIcon';
export { ShareIcon } from './ShareIcon';
export { StepsIcon } from './StepsIcon';
export { ConnectIcon } from './ConnectIcon';
export { PercentIcon } from './PercentIcon';
export { LightThemeIcon } from './LightThemeIcon';
export { DarkThemeIcon } from './DarkThemeIcon';
export { AutoThemeIcon } from './AutoThemeIcon';
export { PinIcon } from './PinIcon';
export { ErrorIcon } from './ErrorIcon';
export { InfoSolidIcon } from './InfoSolidIcon';
