import type { FlagPropTypes, Language } from '@arlert-dev/ui';

import {
  Bengali,
  Catalonia,
  Chinese,
  Denmark,
  English,
  Finland,
  French,
  German,
  Greece,
  Hungary,
  India,
  Indonesian,
  Italian,
  Japanese,
  Korea,
  Lithuania,
  Malay,
  Netherlands,
  Pakistan,
  Philippines,
  Poland,
  Portuguese,
  Russian,
  SaudiArabia,
  Serbia,
  Slovakia,
  SouthAfrica,
  Spanish,
  Swahili,
  Swedish,
  Thai,
  Turkish,
  Ukrainian,
  Vietnamese,
} from '@arlert-dev/ui';

export type LanguageItem = {
  title: string;
  label: string;
  local: Language;
  SVGFlag: React.ComponentType<FlagPropTypes>;
};

export const LANGUAGES: LanguageItem[] = [
  { title: 'Afrikaans', label: 'Afrikaans', local: 'af', SVGFlag: SouthAfrica },
  { title: 'Arabic', label: 'عربي', local: 'ar', SVGFlag: SaudiArabia },
  { title: 'Bengali', label: 'বাংলা', local: 'bn', SVGFlag: Bengali },
  { title: 'Catalan', label: 'Català', local: 'ca', SVGFlag: Catalonia },
  {
    title: 'Chinese (Simplified)',
    label: '简体中文',
    local: 'zh-CN',
    SVGFlag: Chinese,
  },
  {
    title: 'Chinese (Traditional)',
    label: '中文（繁體)',
    local: 'zh-TW',
    SVGFlag: Chinese,
  },
  { title: 'Danish', label: 'Dansk', local: 'da', SVGFlag: Denmark },
  { title: 'Dutch', label: 'Nederlands', local: 'nl', SVGFlag: Netherlands },
  { title: 'English', label: 'English', local: 'en', SVGFlag: English },
  { title: 'Filipino', label: 'Filipino', local: 'fil', SVGFlag: Philippines },
  { title: 'Finnish', label: 'Suomalainen', local: 'fi', SVGFlag: Finland },
  { title: 'French', label: 'Français', local: 'fr', SVGFlag: French },
  { title: 'German', label: 'Deutsch', local: 'de', SVGFlag: German },
  { title: 'Greek', label: 'ελληνικά', local: 'el', SVGFlag: Greece },
  { title: 'Hindi', label: 'हिंदी', local: 'hi', SVGFlag: India },
  { title: 'Hungarian', label: 'Magyar', local: 'hu', SVGFlag: Hungary },
  { title: 'Indonesian', label: 'Indonesia', local: 'id', SVGFlag: Indonesian },
  { title: 'Italian', label: 'Italiana', local: 'it', SVGFlag: Italian },
  { title: 'Japanese', label: '日本語', local: 'ja', SVGFlag: Japanese },
  { title: 'Korean', label: '한국인', local: 'ko', SVGFlag: Korea },
  { title: 'Lithuanian', label: 'Lietuvių', local: 'lt', SVGFlag: Lithuania },
  { title: 'Malay', label: 'Melayu', local: 'ms', SVGFlag: Malay },
  { title: 'Polish', label: 'Polski', local: 'pl', SVGFlag: Poland },
  { title: 'Portuguese', label: 'Português', local: 'pt', SVGFlag: Portuguese },
  { title: 'Russian', label: 'Русский', local: 'ru', SVGFlag: Russian },
  { title: 'Serbian', label: 'Cрпски', local: 'sr', SVGFlag: Serbia },
  { title: 'Slovak', label: 'Slovenský', local: 'sk', SVGFlag: Slovakia },
  { title: 'Spanish', label: 'Español', local: 'es', SVGFlag: Spanish },
  { title: 'Swahili', label: 'Kiswahili', local: 'sw', SVGFlag: Swahili },
  { title: 'Swedish', label: 'Svenska', local: 'sv', SVGFlag: Swedish },
  { title: 'Thai', label: 'แบบไทย', local: 'th', SVGFlag: Thai },
  { title: 'Turkish', label: 'Türkçe', local: 'tr', SVGFlag: Turkish },
  { title: 'Ukrainian', label: 'Yкраїні', local: 'uk', SVGFlag: Ukrainian },
  { title: 'Urdu', label: 'اردو', local: 'ur', SVGFlag: Pakistan },
  {
    title: 'Vietnamese',
    label: 'Tiếng Việt',
    local: 'vi',
    SVGFlag: Vietnamese,
  },
];

export const DEFAULT_LANGUAGE = 'en';
