export const WIDGET_MAX_HEIGHT = '700px';
export const WIDGET_MIN_HEIGHT_FOR_SMALL_SCREENS = '425px';
export const WIDGET_MIN_HEIGHT_FOR_LARGE_SCREENS = '550px';
export const COMPACT_TOKEN_SELECTOR_THRESHOLD = '640px';
export const LARGE_SCREEN_MIN_HEIGHT = '800px';
