import {
  Bengali,
  Catalonia,
  Chinese,
  Cyprus,
  Denmark,
  English,
  Finland,
  French,
  German,
  Greece,
  Hungary,
  India,
  Indonesian,
  Italian,
  Japanese,
  Korea,
  Lithuania,
  Malay,
  Netherlands,
  Pakistan,
  Philippines,
  Poland,
  Portuguese,
  Russian,
  SaudiArabia,
  Serbia,
  Slovakia,
  SouthAfrica,
  Spanish,
  Swahili,
  Swedish,
  Thai,
  Turkish,
  Ukrainian,
  Vietnamese,
} from '@rango-dev/ui';

export const LANGUAGES = [
  { name: 'English', value: 'en', Icon: English },
  { name: 'Spanish', value: 'es', Icon: Spanish },
  { name: 'French', value: 'fr', Icon: French },
  { name: 'Japanese', value: 'ja', Icon: Japanese },
  { name: 'Portuguese', value: 'pt', Icon: Portuguese },
  { name: 'Chinese', value: 'zh', Icon: Chinese },
  { name: 'Russian', value: 'ru', Icon: Russian },
  { name: 'German', value: 'de', Icon: German },
  { name: 'Ukrainian', value: 'uk', Icon: Ukrainian },
  { name: 'Swedish', value: 'sv', Icon: Swedish },
  { name: 'Finnish', value: 'fi', Icon: Finland },
  { name: 'Dutch', value: 'nl', Icon: Netherlands },
  { name: 'Greek', value: 'el', Icon: Greece },
  { name: 'Italian', value: 'it', Icon: Italian },
  { name: 'Polish', value: 'pl', Icon: Poland },
  { name: 'Afrikaans', value: 'af', Icon: SouthAfrica },
  { name: 'Arabic', value: 'ar', Icon: SaudiArabia },
  { name: 'Bengali', value: 'bn', Icon: Bengali },
  { name: 'Catalan', value: 'ca', Icon: Catalonia },
  { name: 'Danish', value: 'da', Icon: Denmark },
  { name: 'Hindi', value: 'hi', Icon: India },
  { name: 'Hungarian', value: 'hu', Icon: Hungary },
  { name: 'Indonesian', value: 'id', Icon: Indonesian },
  { name: 'Korean', value: 'ko', Icon: Korea },
  { name: 'Lithuanian', value: 'lt', Icon: Lithuania },
  { name: 'Malay', value: 'ms', Icon: Malay },
  { name: 'Filipino', value: 'fil', Icon: Philippines },
  { name: 'Serbian', value: 'sr', Icon: Serbia },
  { name: 'Slovak', value: 'sk', Icon: Slovakia },
  { name: 'Swahili', value: 'sw', Icon: Swahili },
  { name: 'Thai', value: 'th', Icon: Thai },
  { name: 'Turkish', value: 'tr', Icon: Turkish },
  { name: 'Urdu', value: 'ur', Icon: Pakistan },
  { name: 'Vietnamese', value: 'vi', Icon: Vietnamese },
  { name: 'Greek(cyprus)', value: 'el-CY', Icon: Cyprus },
  { name: 'Chinese(Traditional)', value: 'zh-TW', Icon: Chinese },
];
