name: Setup Environments
description: 'Setting up Git, NodeJS and authenticate.'

runs:
  using: 'composite'
  steps:
    - name: Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      shell: 'bash'

    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
          
    - name: Install packages
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: 'bash'