import type { WidgetConfig } from '../types';

import { type BlockchainMeta, type Token, TransactionType } from 'rango-sdk';

export interface MockDataSlice {
  _blockchainsMapByName: Map<string, BlockchainMeta>;
  _tokens: Token[];
  config: WidgetConfig;
}

const blockchains: [string, BlockchainMeta][] = [
  [
    'BTC',
    {
      name: 'BTC',
      defaultDecimals: 8,
      addressPatterns: [],
      feeAssets: [
        {
          blockchain: 'BTC',
          symbol: 'BTC',
          address: null,
        },
      ],
      logo: '',
      displayName: 'Bitcoin',
      shortName: 'BTC',
      sort: 1,
      color: '#F7931A',
      enabled: true,
      type: TransactionType.TRANSFER,
      chainId: null,
      info: null,
    },
  ],
  [
    'ETH',
    {
      name: 'ETH',
      defaultDecimals: 18,
      addressPatterns: ['^(0x)[0-9A-Fa-f]{40}$'],
      feeAssets: [
        {
          blockchain: 'ETH',
          symbol: 'ETH',
          address: null,
        },
      ],
      logo: '',
      displayName: 'Ethereum',
      shortName: 'ETH',
      sort: 2,
      color: '#ecf0f1',
      enabled: true,
      type: TransactionType.EVM,
      chainId: '0x1',
      info: {
        infoType: 'EvmMetaInfo',
        chainName: 'Ethereum Mainnet',
        nativeCurrency: {
          name: 'ETH',
          symbol: 'ETH',
          decimals: 18,
        },
        rpcUrls: ['https://rpc.ankr.com/eth'],
        blockExplorerUrls: ['https://etherscan.io'],
        addressUrl: 'https://etherscan.io/address/{wallet}',
        transactionUrl: 'https://etherscan.io/tx/{txHash}',
      },
    },
  ],
  [
    'TRON',
    {
      name: 'TRON',
      defaultDecimals: 18,
      addressPatterns: ['^T[1-9A-HJ-NP-Za-km-z]{33}$'],
      feeAssets: [
        {
          blockchain: 'TRON',
          symbol: 'TRX',
          address: null,
        },
      ],
      logo: '',
      displayName: 'Tron',
      shortName: 'Tron',
      sort: 3,
      color: '#FF060A',
      enabled: true,
      type: TransactionType.TRON,
      chainId: '0x2b6653dc',
      info: {
        addressUrl: '',
        blockExplorerUrls: [],
        chainName: 'TRON',
        infoType: 'TronMetaInfo',
        nativeCurrency: {
          decimals: 10,
          name: 'TRON',
          symbol: 'TRON',
        },
        transactionUrl: '',
      },
    },
  ],
  [
    'POLYGON',
    {
      name: 'POLYGON',
      defaultDecimals: 18,
      addressPatterns: ['^(0x)[0-9A-Fa-f]{40}$'],
      feeAssets: [
        {
          blockchain: 'POLYGON',
          symbol: 'MATIC',
          address: null,
        },
      ],
      logo: '',
      displayName: 'Polygon',
      shortName: 'Polygon',
      sort: 4,
      color: '#8247E5',
      enabled: true,
      type: TransactionType.EVM,
      chainId: '0x89',
      info: {
        infoType: 'EvmMetaInfo',
        chainName: 'Ethereum Mainnet',
        nativeCurrency: {
          name: 'ETH',
          symbol: 'ETH',
          decimals: 18,
        },
        rpcUrls: ['https://rpc.ankr.com/eth'],
        blockExplorerUrls: ['https://etherscan.io'],
        addressUrl: 'https://etherscan.io/address/{wallet}',
        transactionUrl: 'https://etherscan.io/tx/{txHash}',
      },
    },
  ],
  [
    'TON',
    {
      name: 'TON',
      defaultDecimals: 8,
      addressPatterns: [],
      feeAssets: [
        {
          blockchain: 'TON',
          symbol: 'TON',
          address: null,
        },
      ],
      logo: '',
      displayName: 'TON',
      shortName: 'TON',
      sort: 5,
      color: '#F7931A',
      enabled: true,
      chainId: null,
      type: TransactionType.TRANSFER,
      info: null,
    },
  ],
];

const tokens: Token[] = [
  {
    blockchain: 'BTC',
    symbol: 'BTC',
    image: '',
    address: null,
    usdPrice: 72000,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    name: 'Bitcoin',
    decimals: 8,
    isPopular: false,
  },
  {
    blockchain: 'TRON',
    symbol: 'TRX',
    image: '',
    address: '',
    usdPrice: 1,
    isSecondaryCoin: false,
    coinSource: '',
    coinSourceUrl: '',
    name: 'Tron',
    decimals: 8,
    isPopular: false,
  },
  {
    blockchain: 'ETH',
    symbol: 'ETH',
    image: '',
    address: '0xbd6323a83b613f668687014e8a5852079494fb68',
    usdPrice: 4000,
    isSecondaryCoin: false,
    coinSource: '',
    coinSourceUrl: '',
    name: 'Ethereum',
    decimals: 18,
    isPopular: false,
  },
  {
    blockchain: 'TON',
    symbol: 'TON',
    image: '',
    address: null,
    usdPrice: 4050.018,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    name: 'TON',
    decimals: 18,
    isPopular: false,
  },
  {
    blockchain: 'ETH',
    symbol: 'BNB',
    image: '',
    address: null,
    usdPrice: 500,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    name: 'Binance',
    decimals: 18,
    isPopular: false,
  },
  {
    blockchain: 'ETH',
    symbol: 'SOL',
    image: '',
    address: null,
    usdPrice: 150,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    name: 'Solana',
    decimals: 18,
    isPopular: true,
  },
  {
    blockchain: 'BTC',
    symbol: 'KAVA',
    image: '',
    address: null,
    usdPrice: 0.009,
    isSecondaryCoin: true,
    coinSource: null,
    coinSourceUrl: null,
    name: 'KAVA',
    decimals: 18,
    isPopular: false,
  },
  {
    blockchain: 'ETH',
    symbol: 'STALL',
    image: '',
    address: null,
    usdPrice: 150,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    name: 'Stellar long',
    decimals: 18,
    isPopular: false,
  },
  {
    blockchain: 'ETH',
    symbol: 'STALL2',
    image: '',
    address: null,
    usdPrice: 150,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    name: 'Stellar',
    decimals: 18,
    isPopular: false,
  },
  {
    blockchain: 'POLYGON',
    symbol: 'UNI',
    image: '',
    address: null,
    usdPrice: 1.9,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    name: 'Uniswap',
    decimals: 18,
    isPopular: false,
  },
  {
    blockchain: 'POLYGON',
    symbol: 'MATIC',
    image: '',
    address: null,
    usdPrice: 1.9,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    name: 'polygon matic',
    decimals: 18,
    isPopular: false,
  },
  {
    blockchain: 'POLYGON',
    symbol: 'USDT',
    image: '',
    address: null,
    usdPrice: 1.9,
    isSecondaryCoin: false,
    coinSource: null,
    coinSourceUrl: null,
    name: 'tether',
    decimals: 18,
    isPopular: false,
  },
];

export const initialData: MockDataSlice = {
  _tokens: tokens,
  _blockchainsMapByName: new Map<string, BlockchainMeta>(blockchains),
  config: {
    apiKey: '',
    from: {
      pinnedTokens: [
        {
          symbol: 'TON',
          blockchain: 'TON',
          address: null,
        },
      ],
    },
  },
};
