name: Deploy
on:
  workflow_dispatch:
    
jobs:
  deploy-it:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: next
    steps:   
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    

      - name: Prepare
        uses: ./.github/actions/prepare          

      - name: Build & Deploy
        uses: ./.github/actions/build-deploy
        with:
          PLAYGROUND_RANGO_API_KEY: ${{ vars.PLAYGROUND_RANGO_API_KEY }}
          RANGO_API_KEY: ${{ vars.RANGO_API_KEY }}                        
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_WIDGET_CONFIG: ${{ secrets.VERCEL_PROJECT_WIDGET_CONFIG }}
          VERCEL_PROJECT_WIDGET_APP: ${{ secrets.VERCEL_PROJECT_WIDGET_APP }}
          VERCEL_PROJECT_STORYBOOK: ${{ secrets.VERCEL_PROJECT_STORYBOOK }}
          VERCEL_PROJECT_Q: ${{ secrets.VERCEL_PROJECT_Q }}          