name: Publish
on:
  push:
    branches:
      - 'next'
  workflow_dispatch:

  workflow_call:
    
concurrency:
  group: package-publishing

jobs:
  publish:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - run: git pull

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Detect publish flag
        id: flag
        uses: ./.github/actions/detect-publish-flag

      - name: Determine versions
        id: version
        run: yarn run publish:version "$PUBLISH_FLAG"
        env:
          PUBLISH_FLAG: ${{ steps.flag.outputs.flag }}

      - name: Check versions
        run: yarn run publish:version:check
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Version the repository and its clients
        if: steps.version.outputs.count != '0'
        uses: ./.github/actions/release-root
        with:
          flag: ${{ steps.flag.outputs.flag }}

      - name: Publish packages
        run: yarn run publish
        env:
          GH_TOKEN: ${{ github.token }}
          # Github will create .npmrc based on this env variable.
          # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
