name: Production Release
on:
  workflow_dispatch:

jobs:
  sync-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Run Sync Prod
        uses: ./.github/actions/sync-branch
        with:
          prod: true

  publish:
    needs: sync-prod
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  deploy:
    needs: publish
    environment: production
    runs-on: ubuntu-latest
    env:          
      REACT_APP_PLAYGROUND_RANGO_API_KEY: ${{ vars.PLAYGROUND_RANGO_API_KEY }}
      REACT_APP_RANGO_API_KEY: ${{ vars.RANGO_API_KEY }}  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    
          token: ${{ secrets.PAT }}

      - run: git pull
      
      - name: Prepare
        uses: ./.github/actions/prepare                       

      - name: Build & Deploy
        uses: ./.github/actions/build-deploy
        with:
          PLAYGROUND_RANGO_API_KEY: ${{ vars.PLAYGROUND_RANGO_API_KEY }}
          RANGO_API_KEY: ${{ vars.RANGO_API_KEY }}                        
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_WIDGET_CONFIG: ${{ secrets.VERCEL_PROJECT_WIDGET_CONFIG }}
          VERCEL_PROJECT_WIDGET_APP: ${{ secrets.VERCEL_PROJECT_WIDGET_APP }}
          VERCEL_PROJECT_STORYBOOK: ${{ secrets.VERCEL_PROJECT_STORYBOOK }}
          VERCEL_PROJECT_Q: ${{ secrets.VERCEL_PROJECT_Q }}          


  sync-next:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Run Sync Next
        uses: ./.github/actions/sync-branch
