name: Build libraries then upload build artifacts

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build libraries
        run: |
          node ./scripts/build-libs/command.mjs

      - id: upload_artifacts
        name: Upload build artifacts
        uses: ./.github/actions/upload-build-artifacts
